# Generated by Django 3.2.9 on 2021-11-28 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='製品名')),
                ('eng_name', models.CharField(max_length=50, verbose_name='製品名（英語）')),
                ('url_title', models.SlugField(blank=True, max_length=30, verbose_name='urlタイトル')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='images/product/', verbose_name='画像')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='画像url')),
                ('video_url', models.TextField(blank=True, null=True, verbose_name='動画url')),
                ('body', models.TextField(default='', verbose_name='解説')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='概略')),
                ('genre', models.CharField(blank=True, default='merch', max_length=50)),
                ('sub_genre', models.CharField(blank=True, default='others', max_length=255)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('views', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('main_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='メインリンク')),
                ('amazon_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Amazon')),
                ('rakuten_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='楽天')),
                ('suzuri_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='suzuri')),
                ('other_url1', models.CharField(blank=True, max_length=255, null=True, verbose_name='url1')),
                ('other_url2', models.CharField(blank=True, max_length=255, null=True, verbose_name='url2')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='タグ')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='images/post/header', verbose_name='ヘッダー画像')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='画像url')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('abstract', models.TextField(blank=True, max_length=255, verbose_name='概略')),
                ('category', models.CharField(default='others', max_length=255)),
                ('post_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('views', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('state', models.CharField(default='published', max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='タグ')),
            ],
        ),
    ]
