# Generated by Django 6.0.4 on 2026-05-03 12:42

import django.db.models.deletion
import django.utils.timezone
import taggit.managers
import website.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, verbose_name='分野')),
                ('field_eng', models.CharField(max_length=100, verbose_name='英語')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='image_note', verbose_name='カバー画像')),
                ('abstract', models.TextField(blank=True, max_length=255, verbose_name='概略')),
                ('index', models.TextField(default='', verbose_name='目次')),
                ('reference', models.TextField(blank=True, default='', null=True, verbose_name='参考文献')),
                ('ordering', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='科目')),
                ('name_eng', models.CharField(max_length=100, verbose_name='科目（英）')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('url', models.TextField(blank=True, verbose_name='Ad Script')),
                ('click_count', models.IntegerField(default=0)),
                ('shape', models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('square', 'Square')], default='horizontal', max_length=20)),
                ('media', models.CharField(choices=[('amazon', 'Amazon'), ('rakuten', 'Rakuten'), ('suzuri', 'Suzuri'), ('a8', 'A8'), ('others', 'Others')], default='others', max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ad')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=website.models.image_file, verbose_name='画像')),
                ('post_date', models.DateTimeField(auto_now=True, verbose_name='投稿日時')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('quotes', models.TextField(blank=True, default='', null=True, verbose_name='引用')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=website.models.image_note, verbose_name='ヘッダー画像')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='画像url')),
                ('caption', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='画像キャプション')),
                ('video', models.TextField(blank=True, null=True, verbose_name='ビデオ')),
                ('abstract', models.TextField(blank=True, max_length=255, verbose_name='概略')),
                ('intro', models.TextField(blank=True, verbose_name='導入')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('content2', models.TextField(blank=True, default='', verbose_name='内容2')),
                ('reference', models.TextField(blank=True, default='', null=True, verbose_name='参考文献')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('views', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('state', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='website.field')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=website.models.image_post, verbose_name='ヘッダー画像')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='画像url')),
                ('caption', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='画像キャプション')),
                ('abstract', models.TextField(blank=True, max_length=255, verbose_name='概略')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('reference', models.TextField(blank=True, default='', null=True, verbose_name='参考文献')),
                ('category', models.CharField(choices=[('anthropology', '人類学'), ('chemistry', '化学'), ('biology', '生物'), ('environment', '環境'), ('health', '医療と健康'), ('math', '数学'), ('mind', '脳と心'), ('physics', '物理と天文'), ('politics', '政治'), ('technology', 'テクノロジー'), ('merch', 'サイエンスグッズ'), ('others', 'その他')], default='others', max_length=255)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('views', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('state', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='製品名')),
                ('eng_name', models.CharField(max_length=50, verbose_name='製品名（英語）')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=website.models.image_product, verbose_name='画像')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='画像url')),
                ('video_url', models.TextField(blank=True, null=True, verbose_name='動画url')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='概略')),
                ('body', models.TextField(blank=True, default='', verbose_name='解説')),
                ('genre', models.CharField(blank=True, default='雑貨', max_length=50)),
                ('sub_genre', models.CharField(blank=True, default='others', max_length=255)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('views', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('main_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='メインリンク')),
                ('amazon_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Amazon')),
                ('rakuten_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='楽天')),
                ('suzuri_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='suzuri')),
                ('other_url1', models.CharField(blank=True, max_length=255, null=True, verbose_name='url1')),
                ('other_url2', models.CharField(blank=True, max_length=255, null=True, verbose_name='url2')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='タグ')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='website.subject', verbose_name='Subject'),
        ),
        migrations.CreateModel(
            name='NoteView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('count', models.PositiveIntegerField(default=1)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_per_day', to='website.note')),
            ],
            options={
                'unique_together': {('note', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('count', models.PositiveIntegerField(default=1)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_per_day', to='website.post')),
            ],
            options={
                'unique_together': {('post', 'date')},
            },
        ),
    ]
