# Generated by Django 3.2.9 on 2022-01-22 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, verbose_name='分野')),
                ('field_eng', models.CharField(max_length=100, verbose_name='英語')),
                ('subject', models.CharField(max_length=100, verbose_name='科目')),
                ('subj_eng', models.CharField(default='', max_length=100, verbose_name='科目（英）')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=website.models.image_note, verbose_name='カバー画像')),
                ('abstract', models.TextField(blank=True, max_length=255, verbose_name='概略')),
                ('ordering', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('index', models.TextField(default='<h5></h5>\n<ul>\n<li></li>\n</ul>', verbose_name='目次')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='製品名')),
                ('eng_name', models.CharField(max_length=50, verbose_name='製品名（英語）')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=website.models.image_product, verbose_name='画像')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='画像url')),
                ('video_url', models.TextField(blank=True, null=True, verbose_name='動画url')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='概略')),
                ('body', models.TextField(blank=True, default='', verbose_name='解説')),
                ('genre', models.CharField(blank=True, default='雑貨', max_length=50)),
                ('sub_genre', models.CharField(blank=True, default='others', max_length=255)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('views', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('main_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='メインリンク')),
                ('amazon_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Amazon')),
                ('rakuten_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='楽天')),
                ('suzuri_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='suzuri')),
                ('other_url1', models.CharField(blank=True, max_length=255, null=True, verbose_name='url1')),
                ('other_url2', models.CharField(blank=True, max_length=255, null=True, verbose_name='url2')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='タグ')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=website.models.image_post, verbose_name='ヘッダー画像')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='画像url')),
                ('caption', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='画像キャプション')),
                ('abstract', models.TextField(blank=True, max_length=255, verbose_name='概略')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('category', models.CharField(default='others', max_length=255)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('views', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('state', models.CharField(default='published', max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='タグ')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('quotes', models.TextField(blank=True, default='', null=True, verbose_name='引用')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=website.models.image_note, verbose_name='ヘッダー画像')),
                ('caption', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='画像キャプション')),
                ('video', models.TextField(blank=True, null=True, verbose_name='ビデオ')),
                ('abstract', models.TextField(blank=True, max_length=255, verbose_name='概略')),
                ('intro', models.TextField(blank=True, verbose_name='導入')),
                ('table', models.TextField(blank=True, default='<li><a href="#index1"></a></li>\n<li><a href="#index2"></a></li>\n<li><a href="#index3"></a></li>\n<li><a href="#index_ref">参考文献</a></li>', verbose_name='目次')),
                ('content1', models.TextField(default='<h4 id="index1"></h4>\n<p>\n</p>', verbose_name='内容1')),
                ('content2', models.TextField(blank=True, default='', verbose_name='内容2')),
                ('reference', models.TextField(blank=True, default='', null=True, verbose_name='参考文献')),
                ('subject', models.CharField(default='None', max_length=255)),
                ('subj_eng', models.CharField(default='', max_length=255)),
                ('field2', models.CharField(default='None', max_length=255)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('views', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('state', models.CharField(default='published', max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('field1', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='website.field')),
                ('note_tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='タグ')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='製品名')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=website.models.image_product, verbose_name='画像')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='画像url')),
                ('description', models.TextField(blank=True, max_length=900, verbose_name='概略')),
                ('subject', models.CharField(blank=True, default='物理', max_length=50)),
                ('views', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('main_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='メインリンク')),
                ('amazon_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Amazon')),
                ('rakuten_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='楽天')),
                ('suzuri_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='suzuri')),
                ('other_url1', models.CharField(blank=True, max_length=255, null=True, verbose_name='url1')),
                ('other_url2', models.CharField(blank=True, max_length=255, null=True, verbose_name='url2')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book_tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='タグ')),
            ],
        ),
    ]
