# Generated by Django 6.0.4 on 2026-05-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_field_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
