# Generated by Django 3.2.9 on 2021-11-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_products_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
        migrations.AddField(
            model_name='product',
            name='Amazon_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Amazon'),
        ),
        migrations.AddField(
            model_name='product',
            name='Rakuten_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='楽天'),
        ),
        migrations.AddField(
            model_name='product',
            name='other_url1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='url1'),
        ),
        migrations.AddField(
            model_name='product',
            name='other_url2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='url2'),
        ),
        migrations.AddField(
            model_name='product',
            name='suzuri_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='suzuri'),
        ),
    ]
