# Generated by Django 3.2.9 on 2021-12-03 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0003_alter_product_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=website.models.image_post, verbose_name='ヘッダー画像')),
                ('abstract', models.TextField(blank=True, max_length=255, verbose_name='概略')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('subject', models.CharField(default='None', max_length=255)),
                ('field1', models.CharField(default='None', max_length=255)),
                ('field2', models.CharField(default='None', max_length=255)),
                ('post_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('views', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('state', models.CharField(default='published', max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('note_tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='タグ')),
            ],
        ),
    ]
