# Generated by Django 3.2.9 on 2021-11-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_genre_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
