# Generated by Django 3.2.9 on 2021-12-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_note_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='intro',
            field=models.TextField(blank=True, max_length=255, verbose_name='導入'),
        ),
    ]
