# Generated by Django 3.2.9 on 2022-05-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20220508_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content1',
            field=models.TextField(default='<h4 id="index1"></h4>\n<p>\n</p>', verbose_name='内容1'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content2',
            field=models.TextField(blank=True, default='', verbose_name='内容2'),
        ),
        migrations.AlterField(
            model_name='note',
            name='intro',
            field=models.TextField(blank=True, verbose_name='導入'),
        ),
        migrations.AlterField(
            model_name='note',
            name='reference',
            field=models.TextField(blank=True, default='', null=True, verbose_name='参考文献'),
        ),
    ]
