# Generated by Django 3.2.9 on 2021-11-29 06:08

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_category_genre_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=website.models.image_post, verbose_name='ヘッダー画像'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=website.models.image_product, verbose_name='画像'),
        ),
    ]
