# Generated by Django 3.2.9 on 2021-11-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
