# Generated by Django 3.2.9 on 2021-12-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_note_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='table',
            field=models.TextField(blank=True, max_length=500, verbose_name='目次'),
        ),
        migrations.AlterField(
            model_name='note',
            name='intro',
            field=models.TextField(blank=True, max_length=500, verbose_name='導入'),
        ),
    ]
