# Generated by Django 3.2.9 on 2021-11-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20211129_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url_title',
        ),
    ]
