# Generated by Django 3.2.9 on 2021-11-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Amazon_url',
            new_name='amazon_url',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Rakuten_url',
            new_name='rakuten_url',
        ),
    ]
