# Generated by Django 3.2.9 on 2021-11-29 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_product_url_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header_image',
            new_name='main_image',
        ),
    ]
