# Generated by Django 3.2.9 on 2021-12-04 07:24

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_note_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, verbose_name='分野')),
                ('subject', models.CharField(max_length=100, verbose_name='科目')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=website.models.image_note, verbose_name='カバー画像')),
                ('abstract', models.TextField(blank=True, max_length=255, verbose_name='概略')),
            ],
        ),
    ]
