# Generated by Django 3.2.9 on 2021-11-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20211124_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='メインリンク'),
        ),
        migrations.AlterField(
            model_name='product',
            name='body',
            field=models.TextField(default='', verbose_name='解説'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='概略'),
        ),
    ]
