# Generated by Django 3.2.9 on 2021-11-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20211125_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_title',
            field=models.CharField(blank=True, max_length=30, verbose_name='urlタイトル'),
        ),
    ]
