# Generated by Django 3.2.9 on 2021-12-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_product_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
    ]
