# Generated by Django 3.2.9 on 2021-12-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20211204_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='index',
            field=models.TextField(default='', verbose_name='目次'),
        ),
    ]
