# Generated by Django 3.2.9 on 2021-11-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_product_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url_title',
            field=models.SlugField(blank=True, max_length=30, verbose_name='urlタイトル'),
        ),
    ]
