# Generated by Django 3.2.9 on 2021-11-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_product_url_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='eng_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='製品名（英語）'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='製品名'),
        ),
    ]
