# Generated by Django 3.2.9 on 2021-11-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20211125_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='eng_name',
            field=models.CharField(max_length=50, verbose_name='製品名（英語）'),
        ),
    ]
