# Generated by Django 3.2.9 on 2021-11-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_product_eng_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='動画url'),
        ),
    ]
