# Generated by Django 3.2.9 on 2021-11-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_product_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_url',
            field=models.TextField(blank=True, null=True, verbose_name='動画url'),
        ),
    ]
