# Generated by Django 3.2.9 on 2021-12-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_note_subj_eng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='intro',
            field=models.TextField(blank=True, verbose_name='導入'),
        ),
    ]
