# Generated by Django 3.2.9 on 2021-12-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_note_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='reference',
            field=models.TextField(blank=True, default='', verbose_name='参考文献'),
        ),
    ]
