# Generated by Django 3.2.9 on 2021-11-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='画像url'),
        ),
    ]
