# Generated by Django 3.2.9 on 2021-12-17 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_note_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='note',
            name='reference',
            field=models.TextField(blank=True, default='<li></li>', verbose_name='参考文献'),
        ),
        migrations.AlterField(
            model_name='note',
            name='table',
            field=models.TextField(blank=True, default='<li><a href="#index1"></a></li>\n<li><a href="#index_ref">参考文献</a></li>', max_length=500, verbose_name='目次'),
        ),
    ]
