# Generated by Django 3.2.9 on 2021-11-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='abstract',
            field=models.CharField(blank=True, max_length=255, verbose_name='概略'),
        ),
    ]
