# Generated by Django 3.2.9 on 2021-12-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20211217_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(default='<h4 id="index1"></h4>\n<p>\n</p>\n<div class="eq">\n\\begin{align}\n\n\\end{align}\n</div>', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='note',
            name='table',
            field=models.TextField(blank=True, default='<li><a href="#index1"></a></li>\n<li><a href="#index_ref">参考文献</a></li>', verbose_name='目次'),
        ),
    ]
