# Generated by Django 3.2.9 on 2021-12-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20211217_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.AddField(
            model_name='note',
            name='content1',
            field=models.TextField(default='<h4 id="index1"></h4>\n<p>\n</p>\n<div class="eq">\n\\begin{align}\n\n\\end{align}\n</div>', verbose_name='内容1'),
        ),
        migrations.AddField(
            model_name='note',
            name='content2',
            field=models.TextField(blank=True, default='None', verbose_name='内容2'),
        ),
    ]
