# Generated by Django 3.2.9 on 2021-11-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20211127_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.CharField(default='private', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='uncategorized', max_length=255),
        ),
    ]
