# Generated by Django 3.2.9 on 2021-12-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20211218_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content2',
            field=models.TextField(blank=True, default='<h4 id="index4"></h4>', verbose_name='内容2'),
        ),
    ]
