# Generated by Django 3.2.9 on 2021-11-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20211127_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='post_tags',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='genre',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_genre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.CharField(default='published', max_length=255),
        ),
    ]
