# Generated by Django 3.2.9 on 2021-12-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_note_content2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='reference',
            field=models.TextField(blank=True, default='', null=True, verbose_name='参考文献'),
        ),
    ]
