# Generated by Django 3.2.9 on 2021-12-18 04:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_note_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content1',
            field=ckeditor.fields.RichTextField(default='<h4 id="index1"></h4>\n<p>\n</p>\n<div class="eq">\n\\begin{align}\n\n\\end{align}\n</div>', verbose_name='内容1'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content2',
            field=ckeditor.fields.RichTextField(blank=True, default='<h4 id="index4"></h4>', verbose_name='内容2'),
        ),
        migrations.AlterField(
            model_name='note',
            name='intro',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='導入'),
        ),
    ]
