# Generated by Django 3.2.9 on 2021-11-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20211128_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.CharField(blank=True, default='merch', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_genre',
            field=models.CharField(blank=True, default='others', max_length=255),
        ),
    ]
