# Generated by Django 3.2.9 on 2021-12-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20211218_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content1',
            field=models.TextField(default='<h4 id="index1"></h4>\n<p>\n</p>\n<div class="eq">\n\\begin{align}\n\n\\end{align}\n</div>', verbose_name='内容1'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content2',
            field=models.TextField(blank=True, default='<h4 id="index4"></h4>', verbose_name='内容2'),
        ),
        migrations.AlterField(
            model_name='note',
            name='intro',
            field=models.TextField(blank=True, verbose_name='導入'),
        ),
    ]
