# Generated by Django 3.2.9 on 2021-11-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20211128_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product/', verbose_name='画像'),
        ),
    ]
