# Generated by Django 3.2.9 on 2021-12-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20211222_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='画像キャプション'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content1',
            field=models.TextField(default='<h4 id="index1"></h4>\n<p>\n</p>\n<div class="eq">\n\n</div>\n<p>', verbose_name='内容1'),
        ),
    ]
