# Generated by Django 3.2.9 on 2021-12-26 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='subject',
        ),
    ]
