# Generated by Django 3.2.9 on 2022-01-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_auto_20211227_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content1',
            field=models.TextField(default='<h4 id="index1"></h4>\n<p>\n</p>', verbose_name='内容1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='body',
            field=models.TextField(blank=True, default='', verbose_name='解説'),
        ),
    ]
