# Generated by Django 6.0.4 on 2026-05-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='メンバー同士の議論や進捗共有はこちら。', verbose_name='説明文'),
        ),
    ]
