# Generated by Django 6.0.4 on 2026-05-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='likes',
        ),
        migrations.AddField(
            model_name='message',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='メッセージを固定'),
        ),
    ]
