# Generated by Django 6.0.4 on 2026-05-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_message_likes_message_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='receive_notifications',
            field=models.BooleanField(default=True, verbose_name='通知を受け取る'),
        ),
    ]
