# Generated by Django 6.0.4 on 2026-05-26 05:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_message_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='投稿画像'),
        ),
    ]
