# Generated by Django 6.0.4 on 2026-05-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_admin_only',
            field=models.BooleanField(default=False, verbose_name='管理者専用カテゴリ'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_board_admin',
            field=models.BooleanField(default=False, verbose_name='掲示板管理者'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='部屋の説明', verbose_name='説明文'),
        ),
    ]
